#!/usr/bin/env scheme
(import (scheme base) (scheme read) (scheme write) (scheme file) (srfi 69))

(define *stack* '())
(define *memory* (make-hash-table equal?))  
(define *words* (make-hash-table equal?))

(define (push! x) (set! *stack* (cons x *stack*)))
(define (pop!) (let ((x (car *stack*))) (set! *stack* (cdr *stack*)) x))
(define (peek) (car *stack*))

(define (sixth-dup) (push! (peek)))
(define (sixth-drop) (pop!))
(define (sixth-swap) (let ((a (pop!)) (b (pop!))) (push! a) (push! b)))
(define (sixth-over) (let ((a (pop!)) (b (peek))) (push! a) (push! b)))
(define (sixth-+) (let ((b (pop!)) (a (pop!))) (push! (+ a b))))
(define (sixth--) (let ((b (pop!)) (a (pop!))) (push! (- a b))))
(define (sixth-*) (let ((b (pop!)) (a (pop!))) (push! (* a b))))
(define (sixth-/) (let ((b (pop!)) (a (pop!))) (push! (quotient a b))))
(define (sixth-mod) (let ((b (pop!)) (a (pop!))) (push! (remainder a b))))
(define (sixth-=) (let ((b (pop!)) (a (pop!))) (push! (if (equal? a b) 1 0))))
(define (sixth-<) (let ((b (pop!)) (a (pop!))) (push! (if (< a b) 1 0))))
(define (sixth->) (let ((b (pop!)) (a (pop!))) (push! (if (> a b) 1 0))))
(define (sixth-store) (let ((addr (pop!)) (val (pop!))) (hash-table-set! *memory* addr val)))
(define (sixth-load) (let ((addr (pop!))) (push! (if (hash-table-exists? *memory* addr) (hash-table-ref *memory* addr) 0))))

(define (tokenize str)
  (define (char-whitespace? c) (or (char=? c #\space) (char=? c #\tab) (char=? c #\newline) (char=? c #\return)))
  (define (split str) 
    (let ((len (string-length str)) (result '()) (current ""))
      (let loop ((i 0))
        (cond ((>= i len) 
               (if (> (string-length current) 0) 
                   (reverse (cons current result)) 
                   (reverse result)))
              ((char-whitespace? (string-ref str i))
               (when (> (string-length current) 0)
                 (set! result (cons current result))
                 (set! current ""))
               (loop (+ i 1)))
              (else 
               (set! current (string-append current (string (string-ref str i))))
               (loop (+ i 1)))))))
  (map (lambda (token) (cond ((string->number token) => values) (else token))) (split str)))

(define (execute-token token)
  (cond ((number? token) (push! token))
        ((string? token)
         (cond ((string=? token "dup") (sixth-dup))
               ((string=? token "drop") (sixth-drop))
               ((string=? token "swap") (sixth-swap))
               ((string=? token "over") (sixth-over))
               ((string=? token "+") (sixth-+))
               ((string=? token "-") (sixth--))
               ((string=? token "*") (sixth-*))
               ((string=? token "/") (sixth-/))
               ((string=? token "mod") (sixth-mod))
               ((string=? token "=") (sixth-=))
               ((string=? token "<") (sixth-<))
               ((string=? token ">") (sixth->))
               ((string=? token "store") (sixth-store))
               ((string=? token "load") (sixth-load))
               ((string=? token ".") (display (pop!)))
               ((string=? token "cr") (newline))
               ((hash-table-exists? *words* token) (eval-string (hash-table-ref *words* token)))
               (else (push! token))))))

(define (eval-string str) 
  (process-tokens (tokenize str)))

(define (parse-definition tokens)
  (let ((name (car tokens)))
    (let loop ((rest (cdr tokens)) (body '()))
      (cond ((null? rest) (error "Missing ;"))
            ((and (string? (car rest)) (string=? (car rest) ";"))
             (let ((def-str (string-join (reverse (map (lambda (x) (if (number? x) (number->string x) x)) body)) " ")))
               (hash-table-set! *words* name def-str)
               (cdr rest)))
            (else (loop (cdr rest) (cons (car rest) body)))))))

(define (parse-if tokens)
  (let loop ((rest tokens) (if-part '()) (else-part '()) (in-else? #f))
    (cond ((null? rest) (error "Missing then"))
          ((and (string? (car rest)) (string=? (car rest) "then"))
           (let ((condition (pop!)))
             (if (> condition 0)
                 (eval-string (string-join (reverse (map (lambda (x) (if (number? x) (number->string x) x)) if-part)) " "))
                 (eval-string (string-join (reverse (map (lambda (x) (if (number? x) (number->string x) x)) else-part)) " "))))
           (cdr rest))
          ((and (string? (car rest)) (string=? (car rest) "else"))
           (loop (cdr rest) if-part else-part #t))
          (in-else?
           (loop (cdr rest) if-part (cons (car rest) else-part) #t))
          (else
           (loop (cdr rest) (cons (car rest) if-part) else-part #f)))))

(define (string-join lst delim)
  (if (null? lst) ""
      (let loop ((acc (car lst)) (rest (cdr lst)))
        (if (null? rest) acc (loop (string-append acc delim (car rest)) (cdr rest))))))

(define (process-tokens tokens)
  (cond ((null? tokens) #f)
        ((and (string? (car tokens)) (string=? (car tokens) ":"))
         (process-tokens (parse-definition (cdr tokens))))
        ((and (string? (car tokens)) (string=? (car tokens) "if"))
         (process-tokens (parse-if (cdr tokens))))
        ((and (string? (car tokens)) (string=? (car tokens) "loadfile"))
         (when (not (null? (cdr tokens)))
           (load-file (cadr tokens)))
         (process-tokens (cddr tokens)))
        (else (execute-token (car tokens)) (process-tokens (cdr tokens)))))

(define (load-file filename)
  (when (file-exists? filename)
    (call-with-input-file filename
      (lambda (port)
        (let ((content (read-all-chars port)))
          (eval-string content))))))

(define (read-all-chars port)
  (let ((chars '()))
    (let loop ()
      (let ((c (read-char port)))
        (if (eof-object? c)
            (list->string (reverse chars))
            (begin (set! chars (cons c chars)) (loop)))))))

(define (repl)
  (display "SIXTH Interactive\n")
  (let loop ()
    (display "sixth> ")
    (let ((input (read-line)))
      (cond ((eof-object? input) (newline))
            ((string=? input "quit") (display "Goodbye!\n"))
            (else (with-exception-handler
                    (lambda (e) (display "Error: ") (display e) (newline))
                    (lambda () (process-tokens (tokenize input))))
                  (loop))))))

(repl) 